package NormalPractical;

import java.util.*;

public class MultipleException {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

		Scanner s = new Scanner(System.in);
		System.out.println("\n enter the two nummber for addition \n");
		try {

			int a = s.nextInt();
			int b = s.nextInt();
			int c = a + b;
			System.out.println("\n value of two number addition is " + c);
		}

		catch (InputMismatchException ex) {
			System.out.println("Error is \t" + ex);
		} catch (ArithmeticException ex) {
			System.out.println("Error is \t" + ex);
		}

		finally {
			System.out.println("\n End of the Programm\n");
		}

	}

}
